version: '3.8'

services:
  pinot-zookeeper:
    image: zookeeper:3.9.2
    container_name: pinot-zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    healthcheck:
      test: ["CMD", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      retries: 5
      timeout: 5s

  pinot-kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: pinot-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: pinot-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://pinot-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - pinot-zookeeper
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s

  pinot-controller:
    image: apachepinot/pinot:1.2.0
    container_name: pinot-controller
    command: StartController -zkAddress pinot-zookeeper:2181
    ports:
      - "9000:9000"
    depends_on:
      - pinot-kafka
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/health || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s

  pinot-broker:
    image: apachepinot/pinot:latest
    container_name: pinot-broker
    command: StartBroker -zkAddress pinot-zookeeper:2181
    ports:
      - "8099:8099"
    depends_on:
      - pinot-controller
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8099/health || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s

  pinot-server:
    image: apachepinot/pinot:latest
    container_name: pinot-server
    command: StartServer -zkAddress pinot-zookeeper:2181
    ports:
      - "8098:8098"
    depends_on:
      - pinot-broker
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8097/health/readiness || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
#
#  superset_db:
#    image: postgres:13
#    container_name: superset_db
#    environment:
#      - POSTGRES_DB=superset
#      - POSTGRES_USER=superset
#      - POSTGRES_PASSWORD=superset
#    volumes:
#      - superset_db_data:/var/lib/postgresql/data
#    restart: unless-stopped
#
#  superset:
#    image: apache/superset:latest
#    container_name: superset
#    environment:
#      - SUPERSET_LOAD_EXAMPLES=no
#      - SUPERSET_SECRET_KEY=my_superset_secret
#    ports:
#      - "8088:8088"
#    volumes:
#      - superset_home:/app/superset_home
#    command: >
#      sh -c '
#      superset db upgrade &&
#      superset fab create-admin \
#        --username admin \
#        --firstname Superset \
#        --lastname Admin \
#        --email admin@superset.com \
#        --password admin &&
#      superset init &&
#      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
#      '
#    depends_on:
#      - superset_db
#    restart: unless-stopped
#
#volumes:
#  superset_home:
#  superset_db_data:
#
#networks:
#  default:
#    driver: bridge
